version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.8.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow/src     # Ajouter le chemin vers 'src'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags        # Monte ton dossier 'dags'
      - ./src:/opt/airflow/src          # Monte ton dossier 'src'
      - ./data:/opt/airflow/data        # Monte ton dossier 'data'
    depends_on:
      - postgres
    command: airflow webserver
